//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollTex.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColltexEntities : DbContext
    {
        public ColltexEntities()
            : base("name=ColltexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<DetailEPC> DetailEPCs { get; set; }
        public virtual DbSet<EPC> EPCs { get; set; }
        public virtual DbSet<Good> Goods { get; set; }
        public virtual DbSet<PKL> PKLs { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Style> Styles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
